const HOTEL_NAMES = [
    { code: "HOURDU", name: "25hours Hotel One Central" },
    { code: "AQUAAN", name: "AQUAWORLD BELEK" },
    { code: "ARMAKE", name: "ARMAS KAPLAN PARADISE" },
    { code: "ABJADU", name: "Abjad Grand Hotel" },
    { code: "ADDRDU", name: "Address Beach Resort" },
    { code: "ADDRDU", name: "Address Boulevard" },
    { code: "ADDRDU", name: "Address Downtown" },
    { code: "ADDRDU", name: "Address Dubai Mall" },
    { code: "ADDRDU", name: "Address Dubai Marina" },
    { code: "ADDRDU", name: "Address Montgomerie" },
    { code: "ADDRDU", name: "Address Sky View" },
    { code: "ADONAN", name: "Adonis Otel" },
    { code: "ALBADU", name: "Al Bandar Arjaan by Rotana" },
    { code: "ALNADU", name: "Al Naseem Jumeirah" },
    { code: "ALLIBO", name: "Allium Bodrum Resort & Spa Bodrum" },
    { code: "ALOFDU", name: "Aloft Palm Jumeirah" },
    { code: "AMARKE", name: "Amara Luxury Resort" },
    { code: "AMOOAN", name: "Amoon Belek" },
    { code: "ANANDU", name: "Anantara The Palm Resort" },
    { code: "ANDADU", name: "Andaz Dubai The Palm" },
    { code: "ARAVDU", name: "Aravi Hotel" },
    { code: "ARINBO", name: "Arin Resort Bodrum Bodrum" },
    { code: "ARMADU", name: "Armani Hotel Dubai" },
    { code: "ARMOBO", name: "Armonia Holiday Village & Spa Bodrum" },
    { code: "ARTSIS", name: "Arts Hotel Istanbul" },
    { code: "ASKAAN", name: "Aska Lara Resort" },
    { code: "ASKOIS", name: "Askoç Hotel Istanbul" },
    { code: "ASTEAK", name: "Asteria Kremlin Palace" },
    { code: "ATANDU", name: "Atana Hotel" },
    { code: "ATLADU", name: "Atlantis The Palm" },
    { code: "ATROIS", name: "Atro Hotel Istanbul" },
    { code: "AVANDU", name: "Avani Deira Dubai" },
    { code: "AVANDU", name: "Avani Ibn Batuta" },
    { code: "AVANDU", name: "Avani Palm View" },
    { code: "AVANBO", name: "Avantgarde Hotel Yalıkavak - Boutique Class Bodrum" },
    { code: "AVANIS", name: "Avantgarde Urban Hotel Taksim Istanbul" },
    { code: "AYDIAN", name: "Aydinbey Famous Belek" },
    { code: "AYDIAN", name: "Aydinbey Queen's Palace Belek" },
    { code: "AZKABO", name: "Azka Hotel Bodrum" },
    { code: "AZURBO", name: "Azure By Yelken Hotel Bodrum" },
    { code: "BAIAKE", name: "BAIA SALIMA KEMER" },
    { code: "BAIABO", name: "Baia Bodrum Hotel Bodrum" },
    { code: "BARCIS", name: "Barcelo Hotel Istanbul" },
    { code: "BASEMA", name: "Base Selimiye Marmaris" },
    { code: "BEKDIS", name: "Bekdas Hotel Deluxe & Spa Istanbul" },
    { code: "BIRBIS", name: "Birbey Otel Istanbul" },
    { code: "BLUEMA", name: "Blue Bay Platinum Hotel Marmaris" },
    { code: "BLUEBO", name: "Blue Dreams Resort Bodrum" },
    { code: "BODRBO", name: "Bodrium Hotel & Spa Bodrum" },
    { code: "BODRBO", name: "Bodrum Park Resort Hotel Bodrum" },
    { code: "BOHOMA", name: "Boho Garden Selimiye Marmaris" },
    { code: "BURJDU", name: "Burjuman Arjaan By Rotana" },
    { code: "BVLGDU", name: "Bvlgari Resort Dubai" },
    { code: "CCENDU", name: "C Central Resort The Palm" },
    { code: "CALIAN", name: "CALISTA LUXURY BELEK" },
    { code: "CONCAN", name: "CONCORDE DELUXE LARA" },
    { code: "CONRDU", name: "CONRAD" },
    { code: "CAREAL", name: "Caresse" },
    { code: "CARLDU", name: "Carlton Downtown" },
    { code: "CARLDU", name: "Carlton Palace" },
    { code: "CASAMA", name: "Casa De Maris Spa & Resort Hotel Marmaris" },
    { code: "CASABO", name: "Casa Nonna Bodrum Bodrum" },
    { code: "CELAIS", name: "Celal Sultan Hotel Special Class Istanbul" },
    { code: "CLUBFE", name: "Club & Hotel Letoonia Fethiye" },
    { code: "CLUBFE", name: "Club Prive By Rixos Gocek Fethiye" },
    { code: "CLUBFE", name: "Club Tuana Fethiye" },
    { code: "COOKMA", name: "Cook's Club Adakoy Marmaris" },
    { code: "CORADU", name: "Coral Dubai" },
    { code: "CORNAN", name: "Cornelia Diamond Resort" },
    { code: "COURDU", name: "Courtyard By Marriott" },
    { code: "COURDU", name: "Courtyard Culture Village" },
    { code: "CROWDU", name: "Crowne Plaza Dubai" },
    { code: "CROWIS", name: "Crowne Plaza Istanbul" },
    { code: "CRYSAN", name: "Crystal Centro Lara" },
    { code: "CRYSAN", name: "Crystal Sunset Luxury" },
    { code: "CULLAN", name: "Cullinan Belek" },
    { code: "DMARMA", name: "D Maris Bay Marmaris" },
    { code: "DRESFE", name: "D Resort Gocek Fethiye" },
    { code: "DELPAN", name: "DELPHIN BE GRAN" },
    { code: "DELPAN", name: "DELPHIN IMPERIAL" },
    { code: "DAMADU", name: "Damac Maison Distinction" },
    { code: "DELTBO", name: "Delta Hotels By Marriott Bodrum Bodrum" },
    { code: "DIAMBO", name: "Diamond Of Bodrum Bodrum" },
    { code: "DIVAIS", name: "Divan İstanbul" },
    { code: "DORAIS", name: "Dora Hotel Istanbul" },
    { code: "DORIBO", name: "Doria Hotel Bodrum Bodrum" },
    { code: "DOUBBO", name: "Doubletree By Hilton Bodrum Isil Club Resort Bodrum" },
    { code: "DUCAAN", name: "Ducale Lara" },
    { code: "DUJABO", name: "Duja Bodrum Bodrum" },
    { code: "DUKEDU", name: "Dukes The Palm" },
    { code: "DUSIDU", name: "Dusit Thani" },
    { code: "EFTAAL", name: "EFTALIA AQUA RESORT" },
    { code: "ECESFE", name: "Ece Saray Marina & Resort - Special Class Fethiye" },
    { code: "ELEGMA", name: "Elegance Hotels International Marmaris" },
    { code: "ELITDU", name: "Elite Byblos Hotel" },
    { code: "ELITIS", name: "Elite World Comfy İstanbul Taksim" },
    { code: "ELITIS", name: "Elite World İstanbul Taksim" },
    { code: "ELIZMA", name: "Elizya Boutique Otel Marmaris" },
    { code: "FAIRDU", name: "Fairmont" },
    { code: "FAIRDU", name: "Fairmont The Palm" },
    { code: "FAROMA", name: "Faros Premium Beach - Adults Only Marmaris" },
    { code: "FIDAIS", name: "Fidan City Hotel Istanbul" },
    { code: "FLORDU", name: "Flora Al Barsha Mall Of Emirates" },
    { code: "FLORDU", name: "Flora Creek Deluxe Hotel Apartments" },
    { code: "FORTMA", name: "Fortezza Beach Resort Marmaris" },
    { code: "FOURDU", name: "Four Points By Sheraton" },
    { code: "FULLFE", name: "Fullmoon Camping Fethiye" },
    { code: "GARCFE", name: "Garcia Resort & Spa Fethiye" },
    { code: "GEVODU", name: "Gevora Hotel or Voco" },
    { code: "GLORIS", name: "Glorious Hotel İstanbul" },
    { code: "GOLDIS", name: "Golden Age Hotel Istanbul" },
    { code: "GOLDIS", name: "Golden Park Hotel Taksim Istanbul" },
    { code: "GOLDMA", name: "Golden Rock Beach Hotel Marmaris" },
    { code: "GRANAN", name: "Granada Luxury Belek" },
    { code: "GRANAL", name: "Granada Luxury Okurcalar" },
    { code: "GRANDU", name: "Grand Cosmopolitan Hotel" },
    { code: "GRANIS", name: "Grand Emin Istanbul" },
    { code: "GRANDU", name: "Grand Excelsior Hotel" },
    { code: "GRANIS", name: "Grand Hotel Gulsoy" },
    { code: "GRANIS", name: "Grand Hyatt Istanbul" },
    { code: "GRANDU", name: "Grand Millennium Dubai" },
    { code: "GRANAN", name: "Grand Park Lara" },
    { code: "GRANMA", name: "Grand Pasa Hotel Marmaris" },
    { code: "GRANMA", name: "Grand Yazici Marmaris Palace" },
    { code: "GREEBO", name: "Green Bay Resort & Spa Bodrum" },
    { code: "GREEFE", name: "Green Forest Holiday Village Fethiye" },
    { code: "GREEMA", name: "Green Nature Diamond Hotel Marmaris" },
    { code: "GREEMA", name: "Green Nature Resort & Spa Marmaris" },
    { code: "GULFDU", name: "Gulf Court Business Bay" },
    { code: "HABTRE", name: "Habtoor Palace" },
    { code: "HIGHFE", name: "Highclere Hotel And Spa (Adults Only) Fethiye" },
    { code: "HILLBO", name: "Hillstone Bodrum Hotel & Spa Bodrum" },
    { code: "HILTBO", name: "Hilton Bodrum Turkbuku Resort & Spa Bodrum" },
    { code: "HILTDU", name: "Hilton Dubai Creek" },
    { code: "HOLIDU", name: "Holiday Inn Dubai Festival City" },
    { code: "HOLIIS", name: "Holiday Inn Istanbul City by IHG" },
    { code: "HOTEMA", name: "Hotel Aqua - All Inclusive Marmaris" },
    { code: "HOTEDU", name: "Hotel Indigo Dubai Downtown" },
    { code: "HOTEIS", name: "Hotel Lamartine Istanbul" },
    { code: "HOTEIS", name: "Hotel Sultanahmet Istanbul" },
    { code: "HYDEDU", name: "Hyde Hotel Dubai" },
    { code: "HZDHFE", name: "Hzd Hostel Fethiye" },
    { code: "ICHOAN", name: "IC HOTELS SANTAI FAMILY" },
    { code: "ICHOAN", name: "IC Hotels Green Palace" },
    { code: "IKSIFE", name: "Iksirci Baba Hotel Fethiye" },
    { code: "IMPEKE", name: "Imperial Sunland" },
    { code: "INTEDU", name: "Intercontinental Festival" },
    { code: "INTEDU", name: "Intercontinental Residence Suites" },
    { code: "ISTAIS", name: "Istanbul Gonen Hotel" },
    { code: "JURAAN", name: "JURA LARA RESORT" },
    { code: "JAPADU", name: "Ja Palm Tree Court" },
    { code: "JANNDU", name: "Jannah Marina Bay Suites" },
    { code: "JIVAFE", name: "Jiva Beach Resort Fethiye" },
    { code: "JUMEDU", name: "Jumeirah Beach Hotel" },
    { code: "JUMEDU", name: "Jumeirah Creekside Hotel" },
    { code: "JUMEDU", name: "Jumeirah Zabeel Saray" },
    { code: "JUMEDU", name: "Jumeria Rotana" },
    { code: "JWMADU", name: "Jw Marriott Marquis" },
    { code: "KAMEAN", name: "KAMELYA COLLECTION" },
    { code: "KAYAAN", name: "KAYA BELEK" },
    { code: "KAYAAN", name: "KAYA PALAZZO GOLF" },
    { code: "KAYAAN", name: "KAYA SIDE" },
    { code: "KADIBO", name: "Kadikale Resort Bodrum" },
    { code: "KAYABO", name: "Kaya Palazzo Resort & Residences Le Chic Bodrum Bodrum" },
    { code: "KAYAFE", name: "Kayavillas Exclusive Fethiye" },
    { code: "KEFABO", name: "Kefaluka Resort Bodrum" },
    { code: "KEMPDU", name: "Kempinski" },
    { code: "KEMPBO", name: "Kempinski Hotel Barbaros Bay Bodrum" },
    { code: "KEMPDU", name: "Kempinski Mall Of Emirates" },
    { code: "KIRMAN", name: "Kirman Belazure" },
    { code: "KIRMAN", name: "Kirman Calyptus Luxuxry" },
    { code: "KIRMAL", name: "Kirman Leodikya" },
    { code: "KIRMAN", name: "Kirman Sidemarin" },
    { code: "KIRMAL", name: "Kirman Sidra Luxuxry" },
    { code: "KUUMBO", name: "Kuum Hotel & Spa Bodrum" },
    { code: "LIBEAN", name: "LIBERTY LARA" },
    { code: "LABLBO", name: "La Blanche Resort & Spa Bodrum" },
    { code: "LABRMA", name: "Labranda Mares Marmaris" },
    { code: "LABRBO", name: "Labranda Tmt Bodrum Bodrum" },
    { code: "LAPIDU", name: "Lapita" },
    { code: "LARAAN", name: "Lara Barut" },
    { code: "LEMEBO", name: "Le Meridien Bodrum Beach Resort Bodrum" },
    { code: "LEGAIS", name: "Legacy Ottoman Hotel Istanbul" },
    { code: "LIBEFE", name: "Liberty Lykia Fethiye" },
    { code: "LIGHFE", name: "Lighthouse Natalia Aparts Fethiye" },
    { code: "LIMAAN", name: "Limak Lara" },
    { code: "LIURAN", name: "Liu Resort" },
    { code: "LOVFFE", name: "Lov Faralya (+16 Adults Only) Fethiye" },
    { code: "LUJOBO", name: "Lujo Hotel Bodrum Bodrum" },
    { code: "LVZZBO", name: "Lvzz Hotel - Boutique Class- City Center Bodrum" },
    { code: "LYKIAN", name: "Lykia World" },
    { code: "MANEIS", name: "MANESOL GALATA HOTEL Istanbul" },
    { code: "MAXRAN", name: "MAX ROYAL BELEK GOLF" },
    { code: "MIARKE", name: "MIAROSA KEMER BEACH" },
    { code: "MIRAAN", name: "MIRACLE RESORT" },
    { code: "MOVEKE", name: "MOVENPICK RESORT" },
    { code: "MYLOAL", name: "MYLOME LUXURY RESORT" },
    { code: "MANDBO", name: "Mandarin Oriental" },
    { code: "MARCDU", name: "Marco Polo Hotel" },
    { code: "MAREBO", name: "Mare Deluxe Residence Bodrum" },
    { code: "MARMMA", name: "Marmaris Bay Resort By Mp Hotels" },
    { code: "MARTMA", name: "Marti Hemithea Marmaris" },
    { code: "MARTMA", name: "Marti Resort Hotel Marmaris" },
    { code: "MATIIS", name: "Matiat Hotel Istanbul" },
    { code: "MAXXKE", name: "Maxx Royal Kemer Resort" },
    { code: "MDHODU", name: "Md Hotel By Gewan" },
    { code: "MEDIDU", name: "Media Rotana" },
    { code: "MERCDU", name: "Mercure Dubai Barsha Heights" },
    { code: "MIDTIS", name: "Midtown Hotel Istanbul" },
    { code: "MILLDU", name: "Millennium Al Barsha" },
    { code: "MILLDU", name: "Millennium Central" },
    { code: "MILLDU", name: "Millennium Place Marina" },
    { code: "MIMOFE", name: "Mimoza Hotel Fethiye" },
    { code: "MINEIS", name: "Mineo Hotel Taksim Istanbul" },
    { code: "MIRABO", name: "Mirada Exclusive Bodrum Bodrum" },
    { code: "MIVABO", name: "Mivara Luxury Bodrum Bodrum" },
    { code: "MOSCDU", name: "Moscow Hotel" },
    { code: "MYELBO", name: "My Ella Resort & Spa Bodrum" },
    { code: "MVENDU", name: "Mövenpick Jumeirah Lakes Towers" },
    { code: "NGPHKE", name: "NG Phaselis Bay-Kemer" },
    { code: "NIRVAN", name: "NIRVANA Cosmopolitan" },
    { code: "NEWEIS", name: "New Emin Hotel Istanbul" },
    { code: "NIPPIS", name: "Nippon Hotel Istanbul" },
    { code: "NOVAIS", name: "Nova Plaza Crystal Hotel Istanbul" },
    { code: "NOVODU", name: "Novotel Dubai Al Barsha" },
    { code: "ORANAL", name: "ORANGE COUNTY Alanya" },
    { code: "ORANAN", name: "ORANGE COUNTY BELEK" },
    { code: "OAKSDU", name: "Oaks Ibn Battuta Gate Dubai" },
    { code: "OCCIIS", name: "Occidental Taksim Istanbul" },
    { code: "ORKAMA", name: "Orka Lotus Beach Marmaris" },
    { code: "ORKAFE", name: "Orka Sunlife Resort Hotel And Aquapark Fethiye" },
    { code: "PAPIAN", name: "PAPILLON BELVIL HOTEL" },
    { code: "PINEAN", name: "PINE BEACH BELEK" },
    { code: "PORTAN", name: "PORTO BELLO" },
    { code: "PALADU", name: "Palace Downtown" },
    { code: "PALADU", name: "Palazzo Versace Dubai" },
    { code: "PALMBO", name: "Palmalife Bodrum Resort & Spa Bodrum" },
    { code: "PARADU", name: "Paramount Hotel Midtown" },
    { code: "PARKDU", name: "Park Regis Business Bay Hotel" },
    { code: "PERIMA", name: "Perios Beach House - Adults Only Marmaris" },
    { code: "POINIS", name: "Point Hotel Taksim Istanbul" },
    { code: "PREMDU", name: "Premier Inn Dubai Barsha Heights" },
    { code: "PREMDU", name: "Premier Inn Ibn Battuta" },
    { code: "PRIMMA", name: "Prime Beach Hotel Marmaris" },
    { code: "PRIVBO", name: "Prive Hotel Bodrum ( Ex. Voyage Bodrum ) Bodrum" },
    { code: "PULLDU", name: "Pullman Dubai Downtown" },
    { code: "PULLDU", name: "Pullman Dubai Jumeirah" },
    { code: "PULLDU", name: "Pullman Dubai Lakes Towers" },
    { code: "QUEEDU", name: "Queen Elizabeth 2" },
    { code: "RIXOAN", name: "RIXOS PREMIUM" },
    { code: "RIXOAN", name: "RIXOS SUNGATE" },
    { code: "ROYAAN", name: "ROYAL SEGINUS" },
    { code: "RADIIS", name: "Radisson Blu Bosphorus Hotel" },
    { code: "RADIIS", name: "Radisson Blu Hotel" },
    { code: "RADIDU", name: "Radisson Blu Hotel" },
    { code: "RADIDU", name: "Radisson Blu Waterfront" },
    { code: "RADIBO", name: "Radisson Collection Hotel Bodrum Bodrum" },
    { code: "RAMAAN", name: "Ramada Lara" },
    { code: "RAMADU", name: "Ramada Plaza" },
    { code: "RAMABO", name: "Ramada Resort By Wyndham Bodrum Bodrum" },
    { code: "RAMEDU", name: "Ramee Dream Hotel Downtown" },
    { code: "REGNAN", name: "Regnum Carya Golf & Spa" },
    { code: "RENADU", name: "Renaissance Downtown" },
    { code: "RICHIS", name: "Richmond Istanbul" },
    { code: "RIXOKE", name: "Rixos Beldibi" },
    { code: "RIXOAN", name: "Rixos Downtown" },
    { code: "RIXOAN", name: "Rixos Park Belek" },
    { code: "RIXOBO", name: "Rixos Premium Bodrum Bodrum" },
    { code: "RIXODU", name: "Rixos Premium Dubai" },
    { code: "RIXOFE", name: "Rixos Premium Göcek Adult Only Fethiye" },
    { code: "RIXODU", name: "Rixos The Palm" },
    { code: "RODADU", name: "Roda Amwaj Suites" },
    { code: "ROOTBO", name: "Root Redrock Yalikavak Bodrum" },
    { code: "ROOTBO", name: "Root Redrock Yalikavak Bodrum" },
    { code: "ROSEDU", name: "Rose Rayhaan By Rotana" },
    { code: "ROVEDU", name: "Rove Downtown Dubai" },
    { code: "ROVEDU", name: "Rove Dubai Marina" },
    { code: "ROYABO", name: "Royal Asarlik Beach Hotel & Spa Bodrum" },
    { code: "SEVEAN", name: "SEVEN SEAS HOTEL BLUE" },
    { code: "SUSEAN", name: "SUSESI LUXURY BELEK" },
    { code: "SWANAN", name: "SWANDOR HOTELS RESORTS TOPKAPI PALACE" },
    { code: "SALMBO", name: "Salmakis Resort & Spa Bodrum" },
    { code: "SALOFE", name: "Salonika Suites Fethiye" },
    { code: "SAMABO", name: "Samara Hotel Bodrum" },
    { code: "SELEBO", name: "Selectum Collection Bodrum Bodrum" },
    { code: "SELEBO", name: "Selectum Colours Bodrum Bodrum" },
    { code: "SELEAN", name: "Selectum Family Resort" },
    { code: "SELEAN", name: "Selectum Luxury Resort" },
    { code: "SEMIIS", name: "Seminal Hotel Istanbul" },
    { code: "SENSBO", name: "Senses Hotel Bodrum" },
    { code: "SENSAN", name: "Sensetive Resort" },
    { code: "SHANDU", name: "Shangri-la Hotel Dubai" },
    { code: "SHERDU", name: "Sheraton Grand Hotel" },
    { code: "SHERKE", name: "Sherwood Kemer" },
    { code: "SIANBO", name: "Sianji Well-Being Resort Bodrum" },
    { code: "SIREBO", name: "Sirene Luxury Hotel Bodrum Bodrum" },
    { code: "SLSDDU", name: "Sls Dubai Hotel & Residences" },
    { code: "SOFIDU", name: "Sofitel Dubai Downtown" },
    { code: "SOFIDU", name: "Sofitel Dubai Jumeirah" },
    { code: "SOFIDU", name: "Sofitel Dubai The Obelisk" },
    { code: "SOFIDU", name: "Sofitel Dubai The Palm" },
    { code: "SOFIIS", name: "Sofitel İstanbul Taksim" },
    { code: "STARAN", name: "Starlight Resort & Convention Center" },
    { code: "STELDU", name: "Stella Di Mare Dubai Marina" },
    { code: "SUENAN", name: "Sueno Deluxe Belek" },
    { code: "SUNRAN", name: "Sunrise Queen Resort" },
    { code: "SWISDU", name: "Swissotel Al Murooj Dubai" },
    { code: "SWISBO", name: "Swissotel Resort Bodrum Beach Bodrum" },
    { code: "THELAN", name: "THE LAND OF LEGENDS" },
    { code: "TITAAN", name: "TITANIC DELUXE BELEK" },
    { code: "TRENAN", name: "TRENDY LARA" },
    { code: "TUIMAN", name: "TUI MAGIC LIFE BELEK" },
    { code: "TAJEDU", name: "Taj Exotica Resort & Spa" },
    { code: "TAJJDU", name: "Taj Jumeirah Lakes Towers" },
    { code: "TAXIIS", name: "Taxim Express Istanbul" },
    { code: "THEGIS", name: "The Green Park Taksim Istanbul" },
    { code: "THEHDU", name: "The H Dubai" },
    { code: "THEMBO", name: "The Marmara Bodrum - Adult Only Bodrum" },
    { code: "THEMIS", name: "The Marmara Taksim Istanbul" },
    { code: "THEMDU", name: "The Meydan Hotel" },
    { code: "THEPDU", name: "The Palm Managed By Accor" },
    { code: "THEPIS", name: "The Parma Hotel & Spa Taksim Istanbul" },
    { code: "THEPBO", name: "The Plaza Bodrum (Ex. Be Premium Bodrum)" },
    { code: "THERDU", name: "The Radisson Blu Residence" },
    { code: "THERDU", name: "The Retreat Palm MGallery" },
    { code: "THERDU", name: "The Ritz-Carlton" },
    { code: "THETDU", name: "The Tower Plaza Hotel" },
    { code: "TITAIS", name: "Titanic City Taksim Istanbul" },
    { code: "TITAAN", name: "Titanic DELUXE LARA" },
    { code: "TITABO", name: "Titanic Luxury Collection Bodrum Bodrum" },
    { code: "TITAAN", name: "Titanic Mardan Palace" },
    { code: "TOWEDU", name: "Towers Rotana" },
    { code: "TUIBMA", name: "Tui Blue Grand Azur Marmaris" },
    { code: "TUIMBO", name: "Tui Magic Life Bodrum Bodrum" },
    { code: "TURUMA", name: "Turunc Premium Hotel Marmaris" },
    { code: "TURUMA", name: "Turunc Resort Hotel Marmaris" },
    { code: "TWOSDU", name: "Two Seasons Hotel" },
    { code: "UTOPAL", name: "Utopia World Alanya" },
    { code: "VENEAK", name: "Venezia Palace Deluxe Resort" },
    { code: "VERYBO", name: "Very Chic Hotel - Adult Only Bodrum" },
    { code: "VIKIAL", name: "Vikingen Infinity Resort" },
    { code: "VINTDU", name: "Vintage Grand Hotel" },
    { code: "VOCODU", name: "Voco Bonnington Dubai" },
    { code: "VOGUBO", name: "Vogue Hotel Supreme Bodrum Bodrum" },
    { code: "VOXXMA", name: "Voxx Marmaris Beach Hotel - Adult Only" },
    { code: "VOYABO", name: "Voyage Torba Bodrum" },
    { code: "WELLAN", name: "WELL PALACE SIDE" },
    { code: "WHITAL", name: "WHITE CITY RESORT" },
    { code: "WALDDU", name: "Waldorf Astoria Palm Jumeirah" },
    { code: "WYNDDU", name: "Wyndham Residences The Palm" },
    { code: "XANAAN", name: "XANADU RESORT HOTEL" },
    { code: "XANABO", name: "Xanadu Island Hotel Bodrum" },
    { code: "YASAFE", name: "Yasam Park Residence Fethiye" },
    { code: "YASMBO", name: "Yasmin Bodrum Resort Bodrum" },
];

// Additional Turkish cities from hotel data
const ADDITIONAL_HOTEL_CITIES = [
    { code: "RES", name: "& Resorts, Turkey" },
    { code: "ALU", name: "A Luxury Collection Resort & Spa, Turkey" },
    { code: "AKS", name: "Aksu, Turkey" },
    { code: "ALA", name: "Alanya, Turkey" },
    { code: "ANT", name: "Antalya, Turkey" },
    { code: "BOD", name: "Bodrum, Turkey" },
    { code: "BOD", name: "Bodrum Bodrum, Turkey" },
    { code: "DUB", name: "Dubai, Turkey" },
    { code: "DUB", name: "Dubai Parks, Turkey" },
    { code: "FET", name: "Fethiye, Turkey" },
    { code: "IST", name: "Istanbul, Turkey" },
    { code: "IST", name: "Istanbul Sisli, Turkey" },
    { code: "KEM", name: "Kemer, Turkey" },
    { code: "MAR", name: "Marmaris, Turkey" },
];

