"""initial schema from existing tables

Revision ID: c0199cf2b429
Revises: 
Create Date: 2026-06-28 22:15:29.666932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0199cf2b429'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_hotel', schema=None) as batch_op:
        batch_op.drop_column('cost_per_night')

    with op.batch_alter_table('inbound_request', schema=None) as batch_op:
        batch_op.alter_column('nationality',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_inbound_request_parent_request_id'), ['parent_request_id'], unique=False)
        batch_op.create_foreign_key('inbound_request_parent_request_id_fkey', 'inbound_request', ['parent_request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_request', schema=None) as batch_op:
        batch_op.drop_constraint('inbound_request_parent_request_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inbound_request_parent_request_id'))
        batch_op.alter_column('nationality',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('inbound_hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_per_night', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
